### ISSUE TITLE
How cancel chat 

### ISSUE THREAD

**Issue by 4goten** [TheScoutSky/WTab#1]
i alreadly have chat plugin then when i type , the game return 2 messages

**Comment by TheScoutSky** [comment]
Hey, 
thank you for reporting this issue, but this are not enough information for us to fix it. We would like to know:
- What Version are you using?
- Do you have other plugins installed? (When yes which are they)
- Do you run a single minecraft server or a multiple servers via a proxy? (And when, what proxy do you use)

Also we would like to get some screenshots of the problem. Thank you for your help!

TheSkyScout

**Comment by 4goten** [comment]
Version 1.21.1
another chat: CMI
run single minecraft server without proxy
btw i remove cmi chat cuz ur plugin really nice but its seem not support Papi hope it could be added

**Comment by 4goten** [comment]
its inneed collab placeholderApi you made a potential plugin!
